name: todolist
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-339.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.3
  firebase_core: ^2.10.0
  firebase_auth: ^4.4.2
  side_sheet: ^1.0.4  
  flutter_slidable: ^3.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
