// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-GgLbCnkf3nDgM8A07KZJnptoKwVxo-s',
    appId: '1:757214235724:web:0995cb7255bca055d4f8e9',
    messagingSenderId: '757214235724',
    projectId: 'todolist-eb62c',
    authDomain: 'todolist-eb62c.firebaseapp.com',
    storageBucket: 'todolist-eb62c.appspot.com',
    measurementId: 'G-PTJ9NEC3XS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDnH1PIdXav2fIiAO-K8NikgBlu-3zTPkE',
    appId: '1:757214235724:android:ec6108752b67f5abd4f8e9',
    messagingSenderId: '757214235724',
    projectId: 'todolist-eb62c',
    storageBucket: 'todolist-eb62c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC19sR7AWSzNcoJa8itwxa_HW-3TZ-i3U',
    appId: '1:757214235724:ios:2c21992dc26afbdcd4f8e9',
    messagingSenderId: '757214235724',
    projectId: 'todolist-eb62c',
    storageBucket: 'todolist-eb62c.appspot.com',
    iosClientId: '757214235724-b0nuh17l9vrtkicvl9ubls81a4i8s3s8.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC19sR7AWSzNcoJa8itwxa_HW-3TZ-i3U',
    appId: '1:757214235724:ios:9c39d97171da023bd4f8e9',
    messagingSenderId: '757214235724',
    projectId: 'todolist-eb62c',
    storageBucket: 'todolist-eb62c.appspot.com',
    iosClientId: '757214235724-bigk9okget88oem1bb14vfg5bnajsu54.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist.RunnerTests',
  );
}
